src/components/CodeRun.vue, src/components/problem/ProblemListItem.vue, src/types/Problem.ts, src/views/problem/ProblemView.vue
Make the `id` field in the `ProblemInfo` interface optional to enhance type flexibility. Fix the authorization header format in the `CodeRun` component to ensure correct authentication. Adjust styles and layout in the problem view for better readability and visual appeal. Introduce a status mapping for problems to improve the display of problem statuses.
=> Refactor ProblemInfo and improve CodeRun component authentication

src/components/CodeRun.vue, src/components/RecordInfo.vue
- 在 CodeRun 组件中添加 recordInfoRef 引用 RecordInfo 组件
- 在调试和提交前清空 RecordInfo 组件内容
- 在 RecordInfo 组件中添加 clear 方法以支持清空内容
=> refactor(components): 优化 CodeRun 和 RecordInfo 组件交互

src/views/admin/AdminUserView.vue
- 将 Avatar 组件的 info 属性改为 src 属性，以正确显示用户头像
- 修复用户用户名链接的路由参数，使用正确的用户 ID
=> fix(admin): 修复用户列表头像和用户名链接问题

src/stores/user.ts
在用户信息中新增了 signature 字段，用于存储用户的签名或个性宣言。
=> feat(user): 为userStore添加签名字段

src/components/problem/ProblemDifficultySelect.vue, src/components/problem/ProblemSelect.vue, src/components/problem/ProblemStatusSelect.vue
- 优化 ProblemDifficultySelect 和 ProblemStatusSelect 组件的属性类型定义
- 在 ProblemSelect 组件中添加对 ProblemStatusSelect 的引用和重置逻辑
- 在 ProblemStatusSelect 组件中添加重置方法
- 统一重置逻辑，将未选中状态设置为 undefined
=> feat(components): 优化问题筛选重置功能

src/apis/blog.ts
- 在 getBlogListApi 的 URL 中添加结尾斜杠，确保 API 路径的一致性和正确性
=> refactor(apis): 为 getBlogListApi 添加 URL 结尾斜杠

src/apis/user.ts
- 优化了 getUserListApi 和 GetUserInfo 接口的参数定义
- 修改了 ModifyUserInfo 接口，使用 data 对象封装修改信息
- 更新了 ModifyPassword 接口，增加了验证码参数
- 调整了代码格式，提高了可读性
=> refactor(user): 优化用户接口

src/utils/date.ts
- 优化 formatDataTimeStr、formatTimeStr 和 formatDateStr 函数，增加对无效时间字符串的处理
- 使用固定格式输出时间字符串，提高兼容性和准确性
- 添加 futureDate 方法，用于判断给定日期是否在未来
- 增加对未定义和空字符串参数的处理，提高函数的健壮性
=> refactor(utils): 优化时间格式化函数并添加未来日期判断方法

src/utils/date.ts
- 修改 formatDataTimeStr、formatTimeStr 和 formatDateStr 函数
- 使用 toLocaleString() 替代 toISOString()，以适应本地时间格式
- 统一使用 '-' 替代 '/'，保持日期格式一致性
=> refactor(utils): 优化时间格式化函数

src/components/TimeSelect.vue
- 新增 TimeSelect 组件，包含日期和时间选择功能
- 支持禁用未来日期的配置
- 添加自定义占位符和边距样式
- 实现时间选择后的格式化和值更新
=> feat(components): 添加 TimeSelect 组件

src/components/TextEditor.vue, src/router/index.ts, src/views/blog/BlogEditView.vue, src/views/blog/BlogListView.vue, src/views/blog/BlogView.vue
This pull request introduces several enhancements and fixes across multiple files, primarily focusing on the blog editing and viewing functionalities. The most significant changes include the addition of a new blog editing view, modifications to the text editor component, and updates to the blog list and view components to support the new editing capabilities.
* [`src/router/index.ts`](diffhunk://#diff-ed3eadd8a0891daf6ad6d6fabe767371981e5626c8ee467e694455fcbbb63710R116-R124): Added a new route for the blog editing view with the path `/blog/edit`, allowing users with the appropriate permissions to access the blog editor.
* [`src/views/blog/BlogEditView.vue`](diffhunk://#diff-23218e7798f05411083e1f7c7d8b863e4c0d4590fbee995e4731ee35e9decf00R1-R84): Created a new blog editing view, including …
=> Add BlogEditView.vue

src/components/problem/ProblemDifficultySelect.vue, src/components/problem/ProblemSelect.vue, src/components/problem/ProblemStatusSelect.vue, src/components/problem/Problems.vue
- 将 ProblemDifficultySelect 和 ProblemStatusSelect 组件中的 modelValue 属性分别改为 difficulty 和 status
- 更新 ProblemSelect 组件中相关属性和事件的命名
- 调整 Problems 组件中 ProblemSelect 的使用方式
- 优化各组件内部的逻辑和数据处理
=> refactor(components): 重构问题筛选组件的属性命名和事件处理

src/components/judge/LanguageSelect.vue
- 添加 clearable 属性，支持清除选项
- 修改默认值，允许 null 作为有效值
- 在选择框中添加"请选择语言"占位符
=> feat(components): 优化 LanguageSelect 组件

src/components/problem/ProblemSolutionEdit.vue
- 删除了 handleSubmit、handleReset 和 watch 函数中的 console.log 语句
- 优化了代码结构，提高了代码的可读性和性能
=> refactor(components): 移除 ProblemSolutionEdit 组件中的 console.log 语句

src/components/judge/LanguageSelect.vue
- 在 LanguageSelect 组件中添加 placeholder 属性
- 默认值为 "请选择语言"
- 允许通过 props 传递自定义占位符
=> feat(components): 为 LanguageSelect 组件添加自定义占位符

src/types/Blog.ts, src/types/Problem.ts
- 在 BlogInfo 接口中，将 problem_id 和 user_id 字段改为 problem 和 user 字段
- 在 ProblemInfo 接口中，将 user_id 字段改为 user 字段
- 引入 ProblemInfo 和 UserInfo 类型，以提高类型复用性和可维护性
=> refactor(types): 更新 Blog 和 Problem 类型定义

src/components/record/Records.vue, src/types/Record.ts
- 修改 RecordParams 接口中 user 和 problem 字段的类型从 number 改为 string
- 更新 Records.vue 组件中对查询参数的处理，不再进行 parseInt 转换
=> refactor(record): 将记录接口中的 user 和 problem 字段类型改为 string

src/components/record/Records.vue, src/components/user/UserRecord.vue
- 修改 Records.vue 组件，添加 select 属性控制筛选框显示
- 优化 UserRecord.vue 组件，使用 Records.vue 组件显示用户记录
- 在 Records.vue 中添加 userId 和 problemId 属性，用于筛选记录
- 调整布局和逻辑，提高组件的可复用性和灵活性
=> refactor(record): 优化记录组件提高复用性

src/components.d.ts, src/components/HeaderNav.vue
- 更新 components.d.ts，添加 ElCheckboxGroup 类型定义，移除未使用的组件类型
- 重构 HeaderNav 组件，使用计算属性生成菜单项，提高代码可维护性
=> refactor(components): 重构组件类型定义和导航栏

src/components.d.ts, src/router/index.ts, src/views/blog/BlogView.vue, src/views/problem/ProblemView.vue, src/views/record/RecordView.vue, src/views/user/UserSpaceView.vue
This pull request includes changes to dynamically update the document title based on the content of various views in the application. The most important changes are as follows:
Document title updates:
* [`src/router/index.ts`](diffhunk://#diff-ed3eadd8a0891daf6ad6d6fabe767371981e5626c8ee467e694455fcbbb63710R257-R262): Added logic to update the document title based on the `meta.title` property of the route.
* [`src/views/blog/BlogView.vue`](diffhunk://#diff-fed80ca6b7fa2e0876827b31e8be24df583ec6f08da524783265c9792c7e37e2R22): Updated the document title to include the blog title when the component is mounted.
* [`src/views/problem/ProblemView.vue`](diffhunk://#diff-ed00deecf3e48956e245b48ac87c07777a2a204d7ce3888c9e6f75aea306adb7R172): Updated the document title to include the problem ID and …
=> Fix: html title display

src/apis/problem.ts, src/components.d.ts, src/components/judge/LanguageSelect.vue, src/components/problem/TestcaseEdit.vue, src/stores/problemEdit.ts, src/types/Problem.ts, src/views/problem/ProblemEditView.vue, src/views/problem/ProblemView.vue
- 修改 getProblemApi 接口，增加 params 参数以支持选择性获取测试数据和题解
- 更新 problemEditStore 中获取题目信息的逻辑，分别添加获取测试数据和题解的请求
- 调整 ProblemEditView 和 ProblemView 组件，移除不必要的 props，优化数据获取流程
- 将 ElInput 组件替换为 ElInputNumber 组件
- 确保测试点编号只能输入数字，提高数据的准确性
- 在 ProblemInfo 接口中新增 solutions 和 testcases 字段
- 在 ProblemParams 接口中添加对应的查询参数
- 在 ElOption 组件中将 :value="item.id" 修改为 :value="item.id!"，以确保选中值的正确性
- 在 watchEffect 中添加 selectedId.value = props.id，以同步更新选中值
=> 修复编程语言选择器的选中值不一致问题；在 ProblemInfo 接口中添加 solutions 和 testcases 字段 ；将测试点编号输入框改为数字输入框；重构题目相关接口和组件

src/components/user/AvatarInfo.vue, src/stores/user.ts
- 在 userStore 中添加 getUserInfoByUserId 方法，用于获取用户信息
- 优化 AvatarInfo 组件中的信息加载逻辑
- 实现用户信息的缓存和请求去重，提高性能
=> refactor(user): 重构用户信息获取逻辑

src/apis/judge.ts, src/apis/language.ts, src/stores/language.ts
- 删除了未使用的 getLanguageListApi 和 updateLanguageApi
- 移除了无用的导入信息
- 优化了代码结构，提高了代码的可读性和维护性
=> refactor(api): 重构代码并移除未使用的语言相关 API

package-lock.json, package.json, src/assets/style.css, src/components.d.ts, src/views/admin/AdminLanguageView.vue
- 新增 .flex、.flex-col、.gap-* 等通用样式类，便于组件布局
- 添加 .p-4、.rounded、.align-items-stretch 等样式类，增强组件样式表现力
- 新增 .text-red 样式类，用于突出显示错误信息
- 引入 vue-draggable-plus 实现语言拖拽排序
- 优化语言状态更改逻辑
- 添加语言列表批量更新功能
- 重构语言项展示样式
=> 添加通用样式类；重构语言管理功能
